# config/packages/doctrine.yaml
doctrine:
    dbal:
        # on se sert de DATABASE_URL pour que SQLite crée var/data.db automatiquement
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_sqlite'
        charset: UTF8
        server_version: '3.34'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
