security:
    # Configuration des hashages de mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto

    # Configuration du provider d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Configuration des firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            
            # Configuration de la connexion
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_home
                
            # Configuration de la déconnexion
            logout:
                path: app_logout
                target: app_login

            # Configuration des routes protégées
            remember_me:
                secret: 'your_direct_secret_key'
                lifetime: 604800 # 7 jours
                path: /
                
            custom_authenticators:
                - App\Security\GoogleAuthenticator

    # Configuration des routes protégées
    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/register$, roles: PUBLIC_ACCESS }
        - { path: ^/connect/google, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/home, roles: ROLE_USER }
        - { path: ^/account, roles: ROLE_USER }
        - { path: ^/events, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
