#Charger automatiquement toutes les routes définies par attributs (annotations) dans les contrôleurs
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
