app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: [GET]

app_register:
    path: /register
    controller: App\Controller\SecurityController::register
    methods: [GET, POST]

app_home:
    path: /
    controller: App\Controller\SecurityController::login
    methods: [GET]
